import path from 'path';
import fs from 'fs-extra';
import { SANDBOX_ROOT } from '../config';

export interface Template {
  name: string;
  description: string;
  files: { path: string; content: string }[];
}

const TEMPLATES: Template[] = [
  {
    name: 'express-api',
    description: 'A clean Express API with TypeScript, basic routes, and middleware.',
    files: [
      {
        path: 'package.json',
        content: `{
  "name": "{{projectName}}",
  "version": "1.0.0",
  "main": "src/server.ts",
  "scripts": {
    "dev": "ts-node src/server.ts",
    "build": "tsc"
  },
  "dependencies": {
    "express": "^4.18.2",
    "dotenv": "^16.3.1"
  },
  "devDependencies": {
    "typescript": "^5.1.6",
    "ts-node": "^10.9.1",
    "@types/express": "^4.17.17",
    "@types/node": "^20.4.5"
  }
}`
      },
      {
        path: 'src/server.ts',
        content: `import express from 'express';
import dotenv from 'dotenv';

dotenv.config();

const app = express();
const port = process.env.PORT || 3000;

app.use(express.json());

app.get('/', (req, res) => {
  res.json({ message: 'Welcome to {{projectName}} API' });
});

app.listen(port, () => {
  console.log(\`Server running at http://localhost:\${port}\`);
});`
      },
      {
        path: 'tsconfig.json',
        content: `{
  "compilerOptions": {
    "target": "ES2020",
    "module": "CommonJS",
    "outDir": "./dist",
    "rootDir": "./src",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  }
}`
      }
    ]
  },
  {
    name: 'react-component',
    description: 'A premium React component with Tailwind CSS styles.',
    files: [
      {
        path: '{{componentName}}.tsx',
        content: `import React from 'react';

interface {{componentName}}Props {
  title?: string;
  className?: string;
}

export const {{componentName}}: React.FC<{{componentName}}Props> = ({ title = 'Default Title', className = '' }) => {
  return (
    <div className={\`p-6 bg-white rounded-xl shadow-lg hover:shadow-2xl transition-all duration-300 border border-gray-100 \${className}\`}>
      <h2 className="text-2xl font-bold text-gray-800 mb-2">{title}</h2>
      <p className="text-gray-600 leading-relaxed">
        This is a high-quality component generated by the AiAgent.
      </p>
    </div>
  );
};`
      }
    ]
  }
];

export class TemplateService {
  static async generate(templateName: string, targetDir: string, variables: Record<string, string> | undefined = {}): Promise<string[]> {
    const template = TEMPLATES.find(t => t.name === templateName);
    if (!template) throw new Error(`Template '${templateName}' not found.`);

    const generatedFiles: string[] = [];
    const baseDir = path.resolve(SANDBOX_ROOT, targetDir);

    for (const file of template.files) {
      let relativePath = file.path;
      let content = file.content;

      // Simple variable injection
      for (const [key, value] of Object.entries(variables)) {
        const regex = new RegExp(`{{${key}}}`, 'g');
        relativePath = relativePath.replace(regex, value);
        content = content.replace(regex, value);
      }

      const fullPath = path.join(baseDir, relativePath);
      await fs.ensureDir(path.dirname(fullPath));
      await fs.writeFile(fullPath, content, 'utf-8');
      generatedFiles.push(path.join(targetDir, relativePath));
    }

    return generatedFiles;
  }

  static listTemplates() {
    return TEMPLATES.map(t => ({ name: t.name, description: t.description }));
  }
}
